vagrant_box: ubuntu/bionic64
#vagrant_box_version: "20180404.0.0"
vagrant_ip: 192.168.99.
vagrant_hostname: vagrant
vagrant_memory: 3072
vagrant_directory: /vagrant
vagrant_cpu: 1
vagrant_box_check_update: false
vagrant_domain_name: sample.test
vagrant_dns_tld: test

