
- name: Install roles from Ansible Galaxy jenkins
  command: ansible-galaxy install  geerlingguy.jenkins   

- name: Install roles from Ansible Galaxy gitlab
  command: ansible-galaxy install  --roles-path /vagrant/artefacts/playbooks/roles geerlingguy.gitlab   

- name: Install roles from Ansible Galaxy pip
  command: ansible-galaxy install  --roles-path /vagrant/artefacts/playbooks/roles geerlingguy.pip   

- name: Install roles from Ansible Galaxy docker
  command: ansible-galaxy install  --roles-path /vagrant/artefacts/playbooks/roles geerlingguy.docker   

- name: Install roles from Ansible Galaxy service
  command: ansible-galaxy install  --roles-path /vagrant/artefacts/playbooks/roles robertdebock.service   

- name: Install roles from Ansible Galaxy rundeck
  command: ansible-galaxy install  --roles-path /vagrant/artefacts/playbooks/roles robertdebock.rundeck   
