---
- name: Install Docker
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: 'add users to docker group'
      user:
        name: 'vagrant'
        groups: 'docker'
        append: 'yes'
