---
- name: Install Java
  hosts: all
  become: true
  roles:
    - role: geerlingguy.java
      become: yes

  tasks:

  - name: SET IPV4
    shell: echo "export _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true" > /etc/profile.d/java.sh 