---
- name: Install DevOPS
  hosts: all
  become: true
  gather_facts: yes

#  vars_files:
#    - defaults/main.yml

  vars:
    # The URL where Rundeck will be served on:
    roles_path: artefacts/playbooks/roles
    rundeck_port: 4440
    rundeck_address: "{{ ansible_all_ipv4_addresses | default('127.0.0.1') }}"
    rundeck_server_web_context: /
    rundeck_url: "http://{{ rundeck_address }}:{{ rundeck_port }}{{ rundeck_server_web_context }}"
    rundeck_config:
        - parameter: grails.serverURL
          value: "{{ rundeck_url }}"    

- name: Install playbooks Java
  import_playbook: install_java.yaml

- name: Install playbooks Docker
  import_playbook: install_docker.yaml

- name: Install playbooks Jenkins
  import_playbook: install_jenkins.yaml

- name: Install playbooks Gitlab
  import_playbook: install_gitlab.yaml

- name: Install playbooks Rundeck
  import_playbook: install_rundeck.yaml
