---
- name: Install DevOPS
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    # The URL where Rundeck will be served on:
    roles_path: artefacts/playbooks/roles
#    docker_install_compose: true

  tasks:
#    - name: Install Docker
#      apt: name=docker state=latest

#    - name: Install Docker Compose
#      apt: name=docker-compose state=latest
    - name: 2 - Verifique se uma lista de pacotes está instalada
      package:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - docker

    - name: Install Docker
      apt: name=docker state=latest

    - name: Install Boto
      apt: name=python3-boto state=latest

    - name: Install Boto3
      apt: name=python3-boto3 state=latest

    - name: Install Docker Compose
      apt: name=docker-compose state=latest

    - name: 3 - Habilitando Docker CE service no start da máquina
      service:
        name: docker
        state: started
        enabled: yes

    - name: 4 - Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - boto
        - boto3
        - docker-compose

    - name: 'add users to docker group'
      user:
        name: 'digitalhouse'
        groups: 'docker'
        append: 'yes'

    - name: Volume Dockers
      file:
        path: "/var/devops/{{item}}"
        owner: root
        group: digitalhouse
        mode: 0775
        recurse: yes
        state: directory
      with_items: ["jenkins", "rundeck","rundeck-keys", "gitlab","gitgogs"]
   
    - name: Create and start services
      docker_compose:
        project_src: /home/digitalhouse/Documentos/devops/infra-ansible/artefacts/containers
        files:
          - docker-compose.yml