---
- name: Install DevOPS
  hosts: all, localhost
  become: true
  gather_facts: yes

  vars:
    # The URL where Rundeck will be served on:
    roles_path: artefacts/playbooks/roles
    docker_install_compose: true
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:

    - name: 'add users to docker group'
      user:
        name: 'vagrant'
        groups: 'docker'
        append: 'yes'

    - name: Volume Dockers
      file:
        path: "/var/devops/{{item}}"
        owner: root
        group: vagrant
        mode: 0775
        recurse: yes
        state: directory
      with_items: ["jenkins", "rundeck","rundeck-keys", "gitlab","gitgogs"]

    
    - name: Create and start services
      docker_compose:
        project_src: /vagrant/artefacts/containers
        files:
          - docker-compose.yml 

